//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAkademik
    {
        public int id { get; set; }
        public string OgrNo { get; set; }
        public string Dersvehocalar { get; set; }
        public string Yariyil { get; set; }
        public string Vize1 { get; set; }
        public string Vize2 { get; set; }
        public string Final { get; set; }
        public string Ortalama { get; set; }
        public string Harfliortalama { get; set; }
    }
}
