//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyurular
    {
        public int DuyuruID { get; set; }
        public string duyuruBaslik { get; set; }
        public string duyuruIcerik { get; set; }
        public Nullable<System.DateTime> duyuruTar { get; set; }
    }
}
