//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etkinlikler
    {
        public int EtkinlikID { get; set; }
        public string etkinlikBaslik { get; set; }
        public string etkinlikIcerik { get; set; }
        public Nullable<System.DateTime> bitisTar { get; set; }
        public Nullable<System.DateTime> baslangicTar { get; set; }
        public string resim { get; set; }
    }
}
