//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Rezervasyon = new HashSet<Rezervasyon>();
        }
    
        public int KitapID { get; set; }
        public string kitapAd { get; set; }
        public string yazar { get; set; }
        public string Kategori { get; set; }
        public Nullable<int> sayfasayisi { get; set; }
        public string yayinevi { get; set; }
        public string icerik { get; set; }
        public Nullable<int> adet { get; set; }
        public byte[] kitapFoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
    }
}
