//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Rezervasyon = new HashSet<Rezervasyon>();
        }
    
        public int KullaniciID { get; set; }
        public string kullaniciAd { get; set; }
        public string kullanıcıSoyad { get; set; }
        public string mailAdres { get; set; }
        public Nullable<System.DateTime> dogumTar { get; set; }
        public Nullable<int> telefon { get; set; }
        public bool kullaniciTur { get; set; }
        public string girisAdı { get; set; }
        public string sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
    }
}
