//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapKulubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public int RezervasyonID { get; set; }
        public int KitapID { get; set; }
        public int KullanicilarID { get; set; }
        public System.DateTime baslangicTar { get; set; }
        public System.DateTime bitisTar { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
